config/routes.rb
Rails.application.routes.draw do
  root 'books#index'

  resource :users, controller: 'registrations', only:[:create, :edit, :update] do
    get '/sign_up', action: 'new'
  end
  resource :users, controller: 'sessions', only:[] do
    get '/sign_in', action: 'new'
    post '/sign_in', action: 'create'
    delete '/sign_out', action: 'destroy'
  end
  resources :books
  resources :boards
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
  validates :title, presence: true, length: { minimum: 4 }
  validates :chat, presence: true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :name, presence: true, length: { minimum: 4 }
  validates :price, presence: true
  validates :note, presence: true, length: { minimum: 4 }
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true
  validates :email, presence: true, uniqueness: true, format: { with: /[\w]+@([\w-]+\.)+[\w-]{2,4}/ }
  validates :password, presence: true, confirmation: true, length: { minimum:4 }
  validates :nickname, presence: true

  before_create :encrypt_password

  private
  def encrypt_password
    self.password = Digest::SHA1.hexdigest("a#{self.password}z")
  end
  def self.login(user)
    pw = Digest::SHA1.hexdigest("a#{user[:password]}z")
    User.find_by(email: user[:email], password: pw )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  
  rescue_from ActiveRecord::RecordNotFound, with: :record_not_found

  private
  def session_required
    redirect_to sign_in_users_path, notice: '請先登入' unless user_signed_in?
  end
  def record_not_found
    render file: 'public/404.html, layout: false, status: :not_found'
  end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :find_board, only:[:edit, :update, :destroy]
  def index
    @boards = Board.all
  end
  def new
    @board = Board.new
  end
  def create
    @board = Board.new(board_params)
    if @board.save
      redirect_to boards_path, notice: '新增討論區成功'
    else
       render :new
    end
  end
  def edit
  end
  def update
    if @board.update(board_params)
      redirect_to boards_path, notice: '更名討論區成功'
    else
      render :edit
    end
  end
  def destroy
    @board.destroy if @board
    redirect_to boards_path, notice: '討論區已刪除'
  end
  private
  def board_params
    params.require(:board).permit(:title, :chat)
  end
  def find_board
    @board = Board.find_by(id: params[:id])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :find_book, only:[:edit, :update, :destroy]

  def index
    @books = Book.all
  end
  def new
    @book = Book.new
  end
  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to books_path, notice: '新增成功'
    else
      render :new
    end
  end
  def edit
  end
  def update
    if @book.update(book_params)
      redirect_to books_path, notice: '更新成功'
    else
      render :edit
    end 
  end
  def destroy
    @book.destroy if @book
    redirect_to books_path, notice: '刪除成功'
  end
  def show
  end
  private
  def book_params
    params.require(:book).permit(:name, :price, :note)
  end
  def find_book
    @book = Book.find_by(id: params[:id])
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  before_action :session_required, only: [:edit, :update]
  def new
    @user = User.new
  end
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to books_path, notice: '新增成功'
    else
      render :new
    end
  end
  def edit
  end
  def update
    if current_user.update(user_params)
      redirect_to books_path, notice: '資料更新成功'
    else
      #
    end
  end
  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :nickname)
  end
  
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end
  def create
    user = User.login(params[:user])
    if user
      session[:user9527] = user.id
      redirect_to books_path, notice: '登入成功'
    else
      redirect_to sign_in_users_path, notice: '登入失敗'
    end
  end
  def destroy
    session[:user9527] = nil
    redirect_to books_path, notice: '已登出'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    if session[:user9527].present?
      @_user9487 ||= User.find_by(id: session[:user9527])
    else
      nil
    end
  end
  def user_signed_in?
    if current_user
      return true
    else
      return false
    end
  end
end

app/views/boards/edit.html.erb
<h1>編輯看板</h1>

<%= form_for(@board) do |f| %>
<%= f.label :title, '名稱' %>
<%= f.text_field :title %>
<%= f.label :chat, '討論方向' %>
<%= f.text_area :chat %>
<%= f.submit %>
<% end %>
</br>
<%= link_to '看板首頁', boards_path %>

app/views/boards/index.html.erb
<h1>萬寶路的討論區</h1>

<%= link_to '新增討論區', new_board_path %>
<%= link_to '書店', root_path %>

<table>
<thead>
<tr>
<td>討論區名稱</td>
<td>討論區主題</td>
</tr>
</thead>
<tbody>
<% @boards.each do |board| %>
<tr>
<td><%= board.title %></td>
<td><%= board.chat %></td>
<td><%= link_to '編輯', edit_board_path(board) %></td>
<td><%= link_to '刪除', board_path(board), method: 'delete', data: { confirm: '確認刪除' } %></td></tr>
<% end %>
</tbody></table>

app/views/boards/new.html.erb
<h1>新增討論板</h1>

<%= form_for(@board) do |f| %>
<%= f.label :title, '名稱' %>
<%= f.text_field :title %>
<%= f.label :chat, '討論方向' %>
<%= f.text_area :chat %>
<%= f.submit %>
<% end %>
</br>
<%= link_to '看板首頁', boards_path %>

app/views/books/edit.html.erb
<h1>編輯書藉</h1>

<%= form_for(@book) do |f| %>
<%= f.label :name, '書名' %>
<%= f.text_field :name %>
<%= f.label :price, '價格'%>
<%= f.text_field :price %>
<%= f.label :note, '註解' %>
<%= f.text_field :note %>
<%= f.submit %>
<% end %>
</br>
<%= link_to '首頁', root_path %>

app/views/books/index.html.erb
<h1>萬寶路的超級書店</h1>

<%= link_to '新增書藉', new_book_path %>
<%= link_to '討論區', boards_path %>
<%= link_to '註冊', sign_up_users_path %>
<%= link_to '登入', sign_in_users_path %>

</br>
<table>
<thead>
<tr>
<td>書名</td>
<td>價格</td>
<td>註解</td>
</tr>
</thead>
<tbody>
<% @books.each do |book| %>
<tr>
<td><%= book.name %></td>
<td><%= book.price %></td>
<td><%= book.note %></td>
<td><%= link_to '編輯', edit_book_path(book) %></td>
<td><%= link_to '刪除', book_path(book), method: 'delete', data: { confirm: '確認刪除' } %></td>
</tr>
<% end %>
</tbody>
</table>

app/views/books/new.html.erb
<h1>新增書藉</h1>

<%= form_for(@book) do |f| %>
<%= f.label :name, '書名' %>
<%= f.text_field :name %>
<%= f.label :price, '價格'%>
<%= f.text_field :price %>
<%= f.label :note, '註解' %>
<%= f.text_field :note %>
<%= f.submit %>
<% end %>
</br>
<%= link_to '首頁', root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Marlboro</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shard/navbar" %>
    <%= render "shard/flash" if notice %>
    <%= yield %>
  </body>
</html>

app/views/shard/_flash.html.erb
<p><%= notice %></p>

app/views/shard/_navbar.html.erb
<nav>
  <ul>
    <li><%= link_to '新增書藉', new_book_path %></li>
    <li><%= link_to '討論區', boards_path %></li>
  </ul>
  <ul>
    <% if current_user %>
    <li><%= current_user.nickname %></li>
    <li><%= link_to "修改", edit_users_path%></li>
    <li><%= link_to "登出", sign_out_users_path, method: 'delete' %></li>
    <% else %>
    <li><%= link_to "登入", sign_in_users_path %></li>
    <li><%= link_to "註冊", sign_up_users_path %></li>
    <% end %>
  </ul>
</nav>